# Generated by Django 4.2.27 on 2026-05-28 03:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0011_sale_sale_status_created_idx_and_more'),
        ('customers', '0004_customer_payment_submission'),
        ('companies', '0005_alter_product_icon_alter_product_variant_label'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SimStockBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[('main', 'Main stock'), ('customer', 'Customer stock')], max_length=20, verbose_name='location')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='quantity')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sim_stock_balances', to='customers.customer', verbose_name='customer')),
                ('product_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sim_stock_balances', to='companies.productline', verbose_name='product line')),
            ],
            options={
                'verbose_name': 'SIM stock balance',
                'verbose_name_plural': 'SIM stock balances',
                'ordering': ['product_line__sort_order', 'product_line__name', 'customer__name'],
            },
        ),
        migrations.CreateModel(
            name='SimStockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('main_receive', 'Main receive'), ('allocate_to_customer', 'Allocate to customer'), ('return_from_customer', 'Return from customer'), ('adjustment', 'Adjustment'), ('damaged', 'Damaged'), ('sale_consume', 'Sale consume'), ('sale_reversal', 'Sale reversal')], max_length=32, verbose_name='movement type')),
                ('quantity', models.PositiveIntegerField(verbose_name='quantity')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sim_stock_movements_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sim_stock_movements', to='customers.customer', verbose_name='customer')),
                ('from_balance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements_out', to='inventory.simstockbalance', verbose_name='from balance')),
                ('product_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sim_stock_movements', to='companies.productline', verbose_name='product line')),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sim_stock_movements', to='sales.sale', verbose_name='sale')),
                ('to_balance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements_in', to='inventory.simstockbalance', verbose_name='to balance')),
            ],
            options={
                'verbose_name': 'SIM stock movement',
                'verbose_name_plural': 'SIM stock movements',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['movement_type', '-created_at'], name='sim_mov_type_created_idx'), models.Index(fields=['product_line', '-created_at'], name='sim_mov_line_created_idx'), models.Index(fields=['customer', '-created_at'], name='sim_mov_customer_created_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='simstockbalance',
            constraint=models.UniqueConstraint(condition=models.Q(('location', 'main')), fields=('product_line',), name='sim_balance_unique_main_per_line'),
        ),
        migrations.AddConstraint(
            model_name='simstockbalance',
            constraint=models.UniqueConstraint(condition=models.Q(('location', 'customer')), fields=('customer', 'product_line'), name='sim_balance_unique_customer_per_line'),
        ),
        migrations.AddConstraint(
            model_name='simstockbalance',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('customer__isnull', True), ('location', 'main')), models.Q(('customer__isnull', False), ('location', 'customer')), _connector='OR'), name='sim_balance_location_customer_consistent'),
        ),
    ]
