# Generated by Django 4.2.27 on 2026-05-28 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_customer_payment_submission'),
        ('sales', '0013_sim_phase3_4'),
        ('companies', '0007_sim_phase3_4'),
        ('inventory', '0003_simstock_by_product_line'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_or_iccid', models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='serial or ICCID')),
                ('status', models.CharField(choices=[('in_main', 'In main stock'), ('with_customer', 'With customer'), ('consumed', 'Consumed (sold)'), ('damaged', 'Damaged')], default='in_main', max_length=20, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sim_cards', to='customers.customer', verbose_name='customer')),
                ('movement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sim_cards', to='inventory.simstockmovement', verbose_name='movement')),
                ('product_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sim_cards', to='companies.productline', verbose_name='product line')),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sim_cards', to='sales.sale', verbose_name='sale')),
            ],
            options={
                'verbose_name': 'SIM card',
                'verbose_name_plural': 'SIM cards',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['status', 'product_line'], name='sim_card_status_line_idx')],
            },
        ),
    ]
