# Generated by Django 4.2.30 on 2026-08-24 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_sim_phase3_4'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simstockmovement',
            name='movement_type',
            field=models.CharField(choices=[('main_receive', 'Main receive'), ('allocate_to_customer', 'Allocate to customer'), ('return_from_customer', 'Return from customer'), ('adjustment', 'Adjustment'), ('damaged', 'Damaged'), ('manual_sale', 'Manual sale'), ('sale_consume', 'Sale consume'), ('sale_reversal', 'Sale reversal')], max_length=32, verbose_name='movement type'),
        ),
    ]
