# Generated by Django 4.2.27 on 2026-06-03 04:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('phone_refresh', '0018_alter_refreshlog_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsAccessRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=20, verbose_name='number or prefix')),
                ('mode', models.CharField(choices=[('block', 'Block'), ('allow', 'Allow')], default='block', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'SMS access rule',
                'verbose_name_plural': 'SMS access rules',
                'ordering': ['mode', 'value'],
            },
        ),
        migrations.CreateModel(
            name='SmsGatewaySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_enabled', models.BooleanField(default=True, help_text='When off, no real refresh runs; optionally reply with the service-off message.', verbose_name='service enabled')),
                ('send_service_off_reply', models.BooleanField(default=False, verbose_name='reply when service is off')),
                ('service_off_message', models.TextField(blank=True, verbose_name='service-off message')),
                ('replies_master_enabled', models.BooleanField(default=True, help_text='Global kill-switch for ALL outgoing replies (saves SMS consumption).', verbose_name='master replies switch')),
                ('test_number', models.CharField(blank=True, max_length=20, verbose_name='test number')),
                ('test_reply_message', models.TextField(blank=True, default='الخدمة تعمل بشكل سليم.', verbose_name='test reply message')),
                ('claim_timeout_seconds', models.PositiveIntegerField(default=120, help_text='Re-queue a reply if a device claimed it but did not confirm sending in time.', verbose_name='claim timeout (seconds)')),
                ('auto_pause_threshold', models.PositiveIntegerField(default=5, help_text='0 disables auto-pausing devices on repeated send failures.', verbose_name='auto-pause after consecutive failures')),
                ('sender_max_messages', models.PositiveIntegerField(default=0, help_text='0 = no per-sender limit.', verbose_name='max messages per sender')),
                ('sender_window_minutes', models.PositiveIntegerField(default=60, verbose_name='sender window (minutes)')),
                ('global_daily_cap', models.PositiveIntegerField(default=0, help_text='0 = unlimited total replies per day across all devices.', verbose_name='global daily reply cap')),
                ('allowlist_mode', models.BooleanField(default=False, help_text='When on, only numbers in the allow list are processed.', verbose_name='allowlist mode')),
                ('max_send_attempts', models.PositiveIntegerField(default=3, verbose_name='max send attempts')),
                ('log_retention_days', models.PositiveIntegerField(default=0, help_text='0 = keep forever. Older inbound/outbound rows are purged by sms_purge_logs.', verbose_name='log retention (days)')),
                ('heartbeat_alert_minutes', models.PositiveIntegerField(default=10, help_text='Warn when an active device has not contacted the server within this window.', verbose_name='heartbeat alert (minutes)')),
                ('refresh_api_url', models.CharField(blank=True, help_text='Full URL of the refresh API. Leave empty to use the internal phone-refresh endpoint.', max_length=500, verbose_name='refresh API URL')),
                ('refresh_api_token', models.CharField(blank=True, max_length=255, verbose_name='refresh API token')),
                ('refresh_api_timeout', models.PositiveIntegerField(default=30, verbose_name='refresh API timeout (s)')),
                ('refresh_api_phone_field', models.CharField(default='phone_number', max_length=60, verbose_name='phone field name')),
                ('refresh_api_status_path', models.CharField(default='status', max_length=120, verbose_name='status path')),
                ('refresh_api_title_path', models.CharField(default='message.title', max_length=120, verbose_name='title path')),
                ('refresh_api_body_path', models.CharField(default='message.body', max_length=120, verbose_name='body path')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SMS gateway settings',
                'verbose_name_plural': 'SMS gateway settings',
            },
        ),
        migrations.CreateModel(
            name='SmsReplyPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_enabled', models.BooleanField(default=True, verbose_name='reply enabled')),
                ('message_override', models.TextField(blank=True, verbose_name='SMS message override')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sms_reply_policy', to='phone_refresh.refreshstatus')),
            ],
            options={
                'verbose_name': 'SMS reply policy',
                'verbose_name_plural': 'SMS reply policies',
                'ordering': ['status__sort_order', 'status__id'],
            },
        ),
        migrations.CreateModel(
            name='SmsGatewayDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='name')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='phone number')),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('token_prefix', models.CharField(blank=True, max_length=10)),
                ('priority', models.PositiveIntegerField(default=100, help_text='Lower = preferred for sending replies.', verbose_name='priority')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('can_send', models.BooleanField(default=True, help_text='Off = receives only; replies go out from other devices.', verbose_name='can send replies')),
                ('consecutive_failures', models.PositiveIntegerField(default=0)),
                ('auto_paused_at', models.DateTimeField(blank=True, null=True)),
                ('daily_send_limit', models.PositiveIntegerField(default=0, help_text='0 = unlimited for this device.', verbose_name='daily send limit')),
                ('sent_today', models.PositiveIntegerField(default=0)),
                ('sent_today_date', models.DateField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_gateway_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SMS gateway device',
                'verbose_name_plural': 'SMS gateway devices',
                'ordering': ['priority', 'id'],
            },
        ),
        migrations.CreateModel(
            name='InboundSms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_number', models.CharField(db_index=True, max_length=20, verbose_name='from')),
                ('raw_text', models.TextField(blank=True, verbose_name='raw text')),
                ('extracted_number', models.CharField(blank=True, max_length=20, verbose_name='extracted number')),
                ('device_msg_id', models.CharField(blank=True, max_length=80)),
                ('state', models.CharField(choices=[('received', 'Received'), ('processed', 'Processed'), ('ignored', 'Ignored (no valid number)'), ('test', 'Test'), ('blocked', 'Blocked'), ('duplicate', 'Duplicate'), ('rate_limited', 'Rate limited'), ('error', 'Error')], db_index=True, default='received', max_length=20)),
                ('reply_text', models.TextField(blank=True)),
                ('delete_requested', models.BooleanField(db_index=True, default=False)),
                ('delete_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbound_messages', to='sms_gateway.smsgatewaydevice')),
                ('refresh_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_inbound', to='phone_refresh.refreshlog')),
            ],
            options={
                'verbose_name': 'Inbound SMS',
                'verbose_name_plural': 'Inbound SMS',
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='OutboundSms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_number', models.CharField(db_index=True, max_length=20, verbose_name='to')),
                ('body', models.TextField(verbose_name='body')),
                ('state', models.CharField(choices=[('queued', 'Queued'), ('claimed', 'Claimed'), ('sent', 'Sent'), ('failed', 'Failed'), ('dead_letter', 'Dead letter')], db_index=True, default='queued', max_length=20)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('max_attempts', models.PositiveIntegerField(default=3)),
                ('error', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('claimed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_messages', to='sms_gateway.smsgatewaydevice')),
                ('related_inbound', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outbound_messages', to='sms_gateway.inboundsms')),
            ],
            options={
                'verbose_name': 'Outbound SMS',
                'verbose_name_plural': 'Outbound SMS',
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['state', 'created_at'], name='sms_gateway_state_d8d125_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='inboundsms',
            index=models.Index(fields=['state', '-received_at'], name='sms_gateway_state_ef8174_idx'),
        ),
        migrations.AddConstraint(
            model_name='inboundsms',
            constraint=models.UniqueConstraint(condition=models.Q(('device_msg_id__gt', '')), fields=('device', 'device_msg_id'), name='sms_inbound_unique_device_msg'),
        ),
    ]
