# Generated by Django 4.2.30 on 2026-06-04 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_gateway', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsgatewaysettings',
            name='refresh_api_url',
            field=models.CharField(blank=True, help_text='Full URL of an external refresh API. Leave empty to call the internal refresh engine directly (recommended).', max_length=500, verbose_name='refresh API URL'),
        ),
    ]
