# Generated by Django 4.2.27 on 2026-05-24 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('refreshed', 'تم التحديث'), ('not_found', 'غير موجود'), ('wait', 'انتظار'), ('error', 'خطأ')], max_length=20, unique=True)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('body', models.TextField(help_text='Message shown to the customer (Arabic).')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['status'],
            },
        ),
        migrations.CreateModel(
            name='ProviderResponseRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('sky', 'Sky'), ('aloha', 'Aloha'), ('layan', 'Layan'), ('areen', 'Areen')], db_index=True, max_length=20)),
                ('match_type', models.CharField(choices=[('contains', 'Contains (text)'), ('regex', 'Regex (text)'), ('json_path', 'JSON Path (equals)'), ('json_path_contains', 'JSON Path (contains)'), ('status_code', 'HTTP Status')], max_length=20)),
                ('pattern', models.CharField(help_text='Substring, regex, or JSON path expression depending on match type.', max_length=500)),
                ('expected_value', models.CharField(blank=True, help_text='For JSON path / HTTP status: the value to compare against.', max_length=200)),
                ('target_status', models.CharField(choices=[('refreshed', 'تم التحديث'), ('not_found', 'غير موجود'), ('wait', 'انتظار'), ('error', 'خطأ')], max_length=20)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower runs first; first match wins.')),
                ('is_active', models.BooleanField(default=True)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['provider', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RefreshLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(db_index=True, max_length=20)),
                ('provider', models.CharField(blank=True, choices=[('sky', 'Sky'), ('aloha', 'Aloha'), ('layan', 'Layan'), ('areen', 'Areen')], max_length=20)),
                ('status', models.CharField(choices=[('refreshed', 'تم التحديث'), ('not_found', 'غير موجود'), ('wait', 'انتظار'), ('error', 'خطأ')], max_length=20)),
                ('raw_status_code', models.IntegerField(blank=True, null=True)),
                ('raw_excerpt', models.TextField(blank=True, help_text='First ~500 chars of the raw upstream response (for debugging).')),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('matched_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='phone_refresh.providerresponserule')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='providerresponserule',
            index=models.Index(fields=['provider', 'is_active', 'order'], name='phone_refre_provide_169c56_idx'),
        ),
        migrations.AddIndex(
            model_name='refreshlog',
            index=models.Index(fields=['provider', '-created_at'], name='phone_refre_provide_4bd6a3_idx'),
        ),
        migrations.AddIndex(
            model_name='refreshlog',
            index=models.Index(fields=['status', '-created_at'], name='phone_refre_status_3b3837_idx'),
        ),
    ]
