# Generated by Django 4.2.27 on 2026-05-24 22:32

from django.db import migrations, models


NEW_CUSTOMER_MESSAGES = [
    (
        "cooldown",
        "الرجاء الانتظار",
        "لا يمكن تحديث الرقم أكثر من مرة خلال 6 ساعات. مضى على آخر تحديث: {elapsed}.",
    ),
    (
        "service_off",
        "الخدمة متوقفة",
        "خدمة تحديث الأرقام متوقفة مؤقتاً. الرجاء المحاولة لاحقاً.",
    ),
]


def seed_forward(apps, schema_editor):
    SystemSettings = apps.get_model("phone_refresh", "SystemSettings")
    CustomerMessage = apps.get_model("phone_refresh", "CustomerMessage")

    SystemSettings.objects.update_or_create(
        pk=1,
        defaults={
            "service_enabled": True,
            "db_precheck_enabled": True,
            "show_last_refresh": True,
            "cooldown_seconds": 6 * 60 * 60,
            "default_provider": "",
        },
    )

    for status, title, body in NEW_CUSTOMER_MESSAGES:
        CustomerMessage.objects.update_or_create(
            status=status,
            defaults={"title": title, "body": body},
        )


def seed_reverse(apps, schema_editor):
    SystemSettings = apps.get_model("phone_refresh", "SystemSettings")
    CustomerMessage = apps.get_model("phone_refresh", "CustomerMessage")
    SystemSettings.objects.filter(pk=1).delete()
    CustomerMessage.objects.filter(
        status__in=[s for s, *_ in NEW_CUSTOMER_MESSAGES]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('phone_refresh', '0002_seed_defaults'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_enabled', models.BooleanField(default=True, help_text='When off, the public refresh API/page returns the SERVICE_OFF message.')),
                ('db_precheck_enabled', models.BooleanField(default=True, help_text='When on, look up the phone in sales_sale.reference_number to choose the provider. When off, every refresh routes through ``default_provider``.')),
                ('show_last_refresh', models.BooleanField(default=True, help_text='Include last_refresh_at / seconds_since_last_refresh in the public API response.')),
                ('cooldown_seconds', models.PositiveIntegerField(default=21600, help_text='Per-phone cooldown between successful refreshes (in seconds).')),
                ('default_provider', models.CharField(blank=True, choices=[('sky', 'Sky'), ('aloha', 'Aloha'), ('layan', 'Layan'), ('areen', 'Areen')], help_text='Used when DB precheck is disabled. Empty → return ERROR.', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System settings',
                'verbose_name_plural': 'System settings',
            },
        ),
        migrations.AlterField(
            model_name='customermessage',
            name='status',
            field=models.CharField(choices=[('refreshed', 'تم التحديث'), ('not_found', 'غير موجود'), ('wait', 'انتظار'), ('error', 'خطأ'), ('cooldown', 'ضمن فترة الانتظار'), ('service_off', 'الخدمة متوقفة')], max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='providerresponserule',
            name='target_status',
            field=models.CharField(choices=[('refreshed', 'تم التحديث'), ('not_found', 'غير موجود'), ('wait', 'انتظار'), ('error', 'خطأ'), ('cooldown', 'ضمن فترة الانتظار'), ('service_off', 'الخدمة متوقفة')], max_length=20),
        ),
        migrations.AlterField(
            model_name='refreshlog',
            name='status',
            field=models.CharField(choices=[('refreshed', 'تم التحديث'), ('not_found', 'غير موجود'), ('wait', 'انتظار'), ('error', 'خطأ'), ('cooldown', 'ضمن فترة الانتظار'), ('service_off', 'الخدمة متوقفة')], max_length=20),
        ),
        migrations.RunPython(seed_forward, seed_reverse),
    ]
