# Generated by Django 4.2.30 on 2026-05-28 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone_refresh', '0015_sitesettings_public_page_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refreshlog',
            name='source',
            field=models.CharField(choices=[('api', 'API'), ('web', 'Web'), ('employee', 'Employee'), ('internal_test', 'Internal Test'), ('legacy', 'Legacy')], db_index=True, default='web', help_text='Where the refresh attempt was triggered from.', max_length=20),
        ),
    ]
