# Generated by Django 4.2.27 on 2026-06-03 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone_refresh', '0017_sky_sales_portal_rules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refreshlog',
            name='source',
            field=models.CharField(choices=[('api', 'API'), ('web', 'Web'), ('employee', 'المبيعات'), ('sms', 'SMS'), ('internal_test', 'Internal Test'), ('legacy', 'Legacy')], db_index=True, default='web', help_text='Where the refresh attempt was triggered from.', max_length=20),
        ),
    ]
