# Generated by Django 4.2.27 on 2026-05-28 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('sales', '0011_sale_sale_status_created_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='is_new_sim',
            field=models.BooleanField(default=False, verbose_name='new SIM sale'),
        ),
        migrations.AddField(
            model_name='sale',
            name='sim_consumed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='SIM consumed at'),
        ),
        migrations.AddField(
            model_name='sale',
            name='sim_deducted_from',
            field=models.CharField(choices=[('none', 'Not deducted'), ('customer', 'Customer stock'), ('main', 'Main stock')], default='none', max_length=20, verbose_name='SIM deducted from'),
        ),
        migrations.AddField(
            model_name='sale',
            name='sim_stock_movement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumed_sales', to='inventory.simstockmovement', verbose_name='SIM stock movement'),
        ),
    ]
